### ISSUE TITLE
勘误#1

### ISSUE THREAD

**Issue by perryhau** [l11x0m7/book-of-qna-code#1]
P9，定义4 张量（Tensor）：原文“将矢量视为一阶张量”，这句本无问题，但是建议修正为：“将向量（又称矢量）视为一阶张量”。在数学中一般称为向量。
P10，矩阵与矩阵相乘，这节最后一句“矩阵的乘积服从分配率和结合律”，分配率的率应为“律”，即：“矩阵的乘积服从分配律和结合律...”

**Comment by l11x0m7** [comment]
感谢您的勘误，我们会在之后的版本中进行相应修改。
