### ISSUE TITLE
关于第六章使用训练模型进行实际问答任务的Demo

### ISSUE THREAD

**Issue by momo1986** [l11x0m7/book-of-qna-code#10]
您好，感谢分享。
作为本书的忠实读者，想问下，我如果按照第六章的QA问答模型代码进行了训练，在实际业务中怎么部署模型。
比如，给定一个接口，让用户输入问题，输出为问题的答案或“无法回答”。
请问，是否有类似的Demo可以参考？
谢谢啦。

**Comment by l11x0m7** [comment]
你好，

可以把模型权重连同整个graph export出来，然后可以放到远端服务器部署，简单的可以用flask和django这种框架搭建http服务。

demo的话可以具体搜索“tensorflow server部署”和“flask or django”。网上应该有很多示例。

最后，谢谢您阅读本书！
