### ISSUE TITLE
docker pull chatopera/qna-book:1.0.1 unauthorized

### ISSUE THREAD

**Issue by Spackys** [l11x0m7/book-of-qna-code#2]
When I run ./admin/run.sh. It tells me as "Error response from daemon: Get https://registry-1.docker.io/v2/chatopera/qna-bo ok/manifests/1.0.1: unauthorized: incorrect username or password
--". I checked many times about my username and password.Even reset my username and password.But it doesn't working.So is there some permission about download?

**Comment by l11x0m7** [comment]
@Samurais

**Comment by Samurais** [comment]
1) 在hub.docker注册账号https://hub.docker.com/

2) Run```docker login```，使用1)中的用户名和密码登录。
